/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FnSchema: typeof import('./src/lib/components/fn-schema.vue')['default']
    FnUploadDnd: typeof import('./src/lib/components/naive-ui/fn-upload-dnd.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NIcon: typeof import('naive-ui')['NIcon']
    NP: typeof import('naive-ui')['NP']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDnd: typeof import('./src/lib/components/naive-ui/n-upload-dnd.vue')['default']
    Test: typeof import('./src/lib/components/test.vue')['default']
  }
}
